### ISSUE TITLE
JOSS Review: installation fails for python 3.13.0

### ISSUE THREAD

**Issue by erexer** [swiss-seismological-service/DUGseis#16]
This is for the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6768).

Installation fails for python 3.13.0

```bash
pip install -e .                                 ✔ │ 3.13.0rc3t  │ 10:37:20
Obtaining file:///<filepath>/DUGseis
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting click (from DUG-Seis==0.3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting joblib (from DUG-Seis==0.3)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib (from DUG-Seis==0.3)
  Downloading matplotlib-3.9.2-cp313-cp313t-macosx_10_13_x86_64.whl.metadata (11 kB)
Collecting numba (from DUG-Seis==0.3)
  Downloading numba-0.60.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 8.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/<filepath>/DUGseis/.venv3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/<filepath>/DUGseis/.venv3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/<filepath>/DUGseis/.venv3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/81/h441ylh90yn8p6cmrrlp17w00000gn/T/pip-build-env-9_tmulqo/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/81/h441ylh90yn8p6cmrrlp17w00000gn/T/pip-build-env-9_tmulqo/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/81/h441ylh90yn8p6cmrrlp17w00000gn/T/pip-build-env-9_tmulqo/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/81/h441ylh90yn8p6cmrrlp17w00000gn/T/pip-build-env-9_tmulqo/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by mrosskopf** [comment]
The python version is too high for now. It works stable with python 3.11. Therefore, in the installation description, the python version for the conda environment is fixed to 3.11.
I also added it again to the Dependencies part in the documentation where I state now python=3.11 instead of >=3.9
I hope this is fine like that.

**Comment by erexer** [comment]
Ah, ok. You should also change the python version in the [`pyproject.toml`](https://github.com/swiss-seismological-service/DUGseis/blob/main/pyproject.toml#L23).

**Comment by mrosskopf** [comment]
Of course! Done!

**Comment by erexer** [comment]
I'm getting this error now:
```bash
raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.requires-python`.
      configuration error: `project.requires-python` must be pep508-versionspec
```

**Comment by mrosskopf** [comment]
Fixed!

**Comment by erexer** [comment]
You're doing a great job, but this review is taking a lot of time because I'm testing/debugging your code, which is not the role of a reviewer. The `pyproject.toml` is still incorrect, let me know when it's fixed and I'll continue the review.

**Comment by krischer** [comment]
@erexer Thanks a lot for all your work in the review.

We just relaxed the version constraint a bit [here](https://github.com/swiss-seismological-service/DUGseis/commit/4e6e6661779e27891f3374c0d0526c57be6ee1fa). Instead of being hard-coded it now only requires a Python version of at least 3.11.

It will currently work with 3.11 and 3.12 (and I just tested this with two clean environments); 3.13 will currently not work due `numba` still requiring an update (they typically take up to one year after a new release) but as soon as `numba` updates, it should work with our package.

In case it still does not work, please let us know the error you encounter.

All the best!

**Comment by krischer** [comment]
One could of course argue that we should also fix the Python version to be smaller than 3.13 but I'd typically go with the advice in this blog post to not do that: https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special

Once all the dependencies work, DUGseis will likely also work with 3.13 without requiring a code change.

**Comment by erexer** [comment]
Thanks for sharing that article, that's great to know! The install/versioning looks good to me.

**Comment by erexer** [comment]
Can you change the version listed in the [docs](https://dugseis.readthedocs.io/en/latest/installation.html).

**Comment by mrosskopf** [comment]
I updated the version in the documentation to python >= 3.11.
